# Brew Formulae
brew "bat"
brew "cmake"
brew "fnm"
brew "helix"
brew "lazygit"
brew "lsd"
brew "mole"
brew "pyrefly"
brew "ruff"
brew "starship"
brew "tmux"
brew "uv"

# Brew Casks
cask "antigravity-ide"
cask "font-geist-mono"
cask "font-pretendard"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "iina"
cask "keka"
cask "notion"
cask "ollama-app"
cask "orbstack"
cask "raycast"
cask "tableplus"
cask "thaw"
cask "transmission"
cask "tunnelblick"
